config/routes.rb
Rails.application.routes.draw do
  get 'sessions_student/new'
  root 'home_pages#home'
  get 'home_pages/home'
  get 'home_pages/student_create_account', to: 'students#signup'
  post 'home_pages/student_create_account', to: 'students#signup'
  get 'home_pages/admin_create_account', to: 'admins#new'
  get 'home_pages/admin_login', to: 'sessions#new'
  post 'home_pages/admin_login', to: 'sessions#create'
  delete 'home_pages/admin_logout', to: 'sessions#destroy'
  get 'home_pages/student_login', to: 'sessions_student#new'
  post 'home_pages/student_login', to: 'sessions_student#create'
  delete 'home_pages/student_logout', to: 'sessions_student#destroy'
  get 'admin_pages/home'
  get 'student_pages/home'
  get 'student_pages/eval'
  

  get 'admin_pages/home'
  get 'admin_pages/roster'
  get 'admin_pages/projects'
  get 'admin_pages/teams'
  get 'admin_pages/teamParams'
  post 'admin_pages/teamParams'
  get 'student_on_teams/index'
  

  # comment out this root to merge back with normal functionality'
  


  resources :student_on_teams
  resources :works_ons
  resources :submissions
  resources :evaluates
  resources :projects
  resources :teams
  resources :students
  resources :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/evaluate.rb
class Evaluate < ApplicationRecord
  belongs_to :student, optional: true
  belongs_to :project, optional: true
  belongs_to :sender, :class_name => 'Student', optional: true
  belongs_to :recipient, :class_name => 'Student', optional: true
end

app/controllers/evaluates_controller.rb
class EvaluatesController < ApplicationController
  before_action :set_evaluate, only: %i[ show edit update destroy ]

  # GET /evaluates or /evaluates.json
  def index
    @evaluates = Evaluate.all
  end

  # GET /evaluates/1 or /evaluates/1.json
  def show
  end

  # GET /evaluates/new
  def new
    @evaluate = Evaluate.new
    @student = Student.find_by(id: current_user_student)
    @team = @student.teams[0]
    @teammates = @team.students
  end

  # GET /evaluates/1/edit
  def edit
  end

  # POST /evaluates or /evaluates.json
  def create
    @evaluate = Evaluate.new(evaluate_params)
    @evaluate.student_id = current_user_student.id
    @evaluate.sender_id = current_user_student.id

    respond_to do |format|
      if @evaluate.save
        format.html { redirect_to '/evaluates/new', notice: "Evaluate was successfully created." }
        format.json { render :show, status: :created, location: @evaluate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @evaluate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluates/1 or /evaluates/1.json
  def update
    respond_to do |format|
      if @evaluate.update(evaluate_params)
        format.html { redirect_to evaluate_url(@evaluate), notice: "Evaluate was successfully updated." }
        format.json { render :show, status: :ok, location: @evaluate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @evaluate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluates/1 or /evaluates/1.json
  def destroy
    @evaluate.destroy

    respond_to do |format|
      format.html { redirect_to evaluates_url, notice: "Evaluate was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluate
      @evaluate = Evaluate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def evaluate_params
      params.require(:evaluate).permit(:rating, :comments, :project_id, :recipient_id)
    end
end

app/helpers/evaluates_helper.rb
module EvaluatesHelper
end

app/views/evaluates/_form.html.erb
<%= form_with(model: evaluate) do |form| %>
  <% if evaluate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evaluate.errors.count, "error") %> prohibited this evaluate from being saved:</h2>

      <ul>
        <% evaluate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= form.label :student, "Team Member" %>
    <%= form.collection_select :recipient_id, @teammates.order(:fname),:id, :fname, include_blank: false%>
  </div>
  

  <div class="field">
    <%= form.label :project, "Project" %>
    <%= form.collection_select :project_id, Project.order(:projectName),:id,:projectName, include_blank: false %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/evaluates/edit.html.erb
<h1>Editing Evaluate</h1>

<%= render 'form', evaluate: @evaluate %>

<%= link_to 'Show', @evaluate %> |
<%= link_to 'Back', evaluates_path %>

app/views/evaluates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Evaluates</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluates.each do |evaluate| %>
      <tr>
        <td><%= evaluate.rating %></td>
        <td><%= evaluate.comments %></td>
        <td><%= link_to 'Show', evaluate %></td>
        <td><%= link_to 'Edit', edit_evaluate_path(evaluate) %></td>
        <td><%= link_to 'Destroy', evaluate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evaluate', new_evaluate_path %>

app/views/evaluates/new.html.erb
<% provide(:title, "New Evaluation")%>
<h1>New Evaluate</h1>

<%= render 'form', evaluate: @evaluate %>

<%= link_to 'Back', '/student_pages/home' %>

app/views/evaluates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @evaluate.rating %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @evaluate.comments %>
</p>

<%= link_to 'Edit', edit_evaluate_path(@evaluate) %> |
<%= link_to 'Back', evaluates_path %>